### ISSUE TITLE
Sound gap when loop = true

### ISSUE THREAD

**Issue by wmonecke** [thangngoc89/react-howler#129]
Hey there!

I noticed that when loop={true} then a small silent gap is noticeable when the track is about to play again.

Is this intended or am I doing something wrong?

Thank you for your help again!

**Comment by Stenerson** [comment]
This isn't intentional, per say, but it's probably also not an issue with react-howler itself. It certainly *could be* but my guess is that this is probably an upstream question with how howler itself works (or is configured). I'd maybe start by reading through some of their issues (open and or closed) to see if it helps?

https://github.com/goldfire/howler.js/search?q=loop+delay&type=issues

https://github.com/goldfire/howler.js/search?q=seamless+loop&type=issues

**Comment by wmonecke** [comment]
I just encountered this issue [https://github.com/goldfire/howler.js/issues/39](https://github.com/goldfire/howler.js/issues/39). I will try with files other than mp3s.

**Comment by wmonecke** [comment]
For anyone encountering this issue, you need to convert the file to .ogg with the audacity app (not with a web-app converter like I was doing).
