### ISSUE TITLE
Examples do not play sound on ipad

### ISSUE THREAD

**Issue by FutureKode** [thangngoc89/react-howler#38]
Hello,

On my ipad there is no sound when playing the examples [here](https://khoanguyen.me/react-howler/)

This is my browser details http://whatsmybrowser.org/b/XDZORXU

**Comment by thangngoc89** [comment]
I can configrm this. Doesn't work on my iPad too (and probably others iOS devices with the same iOS version).

**Comment by thangngoc89** [comment]
@FutureKode could you test on https://howlerjs.com/ (just play any example) ?

**Comment by FutureKode** [comment]
@thangngoc89 Hi, I tested the demos on howlerjs.com and they work on my ipad.

**Comment by Stenerson** [comment]
Thanks for reporting @FutureKode. This is working on my iPhone in both Safari and Chrome on iOS 10.3.2. I don't have an iOS 9 device with me at the moment but I'll be able to check this later in the day. Stay tuned...

**Comment by thangngoc89** [comment]
@Stenerson hum. Seems like this is a iPad stuff. My iPad is using iOS 10.3.x

**Comment by Stenerson** [comment]
😱 The examples are working on both of my iPads in Safari and Chrome (as well as my iPhone)
- iPad 3 - iOS 9.3.5
- iPad Pro 10.5" - iOS 10.2.3
- iPhone 7 Plus - iOS 10.2.3

Any ideas?

**Comment by thangngoc89** [comment]
I just test again and now it's working on my iPad Mini 3 - iOS 10.3.1

Maybe this has something to do with the fact that the audio needs to be fully loaded before howler.js can start playing it?

**Comment by Stenerson** [comment]
It could be. There's no UI in the examples that indicates loading status (an example problem, rather than a howler or react-howler problem). I'm sure you know, but it's worth reiterating for people who find this issue - Howler does queue calls to `play` (and other methods) and will execute them once the sound is loaded. So it should play, it might just be delayed for longer than you'd expect.

Most of the examples autoload the sound files too. So if you load the page, then wait a few seconds (or longer if you have spotty internet) you might have better luck if it's a loading issue.

Additional anecdote: I'm using react-howler in production and most of my customers use iPads. Audio playback is not a central feature of my product so it's not used a ton but iPad playback is my main use of react-howler in the real world.

@FutureKode any thoughts on this? Are you able to connect to safari to see if there are any messages in the console?

**Comment by FutureKode** [comment]
@thangngoc89 @Stenerson Hi guys, I plugged in my ipad (ipad mini version 1, late 2012), and inspected the reacthowler.js examples page.... nothing in console. All the assets seem to load fine in the network tab.

I have had the page open and then waited for minutes before trying to click play but still no sound.

The 'full control' example shows the status playing along but still no sound.

I can play sound on other websites on this ipad. Thanks guys.

**Comment by FutureKode** [comment]
@thangngoc89 @Stenerson Hi guys, i just checked the examples on another iPad (mini version 2 iOS 10) and their were no problems. It seems the issue is related either to older iPad's running iOS 9... or just a strange issue with my iPad! how strange!

**Comment by FutureKode** [comment]
Guys, I'm terribly sorry, my iPad was muted 😊

**Comment by Stenerson** [comment]
No worries @FutureKode, it happens to the best of us! 😄 
Thanks for following up.

**Comment by StephenGrable1** [comment]
+1 for un-muting your mobile devices 👍 🤦‍♂️
