### ISSUE TITLE
Typings for TypeScript

### ISSUE THREAD

**Issue by maksimovicdanijel** [thangngoc89/react-howler#75]
Hi,

thanks for great library 👍 I'm using React Howler in a TypeScript project and types for this lib are missing. I'm wondering would you accept a PR that would add `index.d.ts` file with typings? If not that's ok too, I can add those in DefinitelyTyped project. @thangngoc89 thanks!

**Comment by Stenerson** [comment]
Thank you for the consideration @maksimovicdanijel. I agree with @thangngoc89's take on this. I'd also be concerned taking this on since I don't personally use TS at this time. This library is quite small, doesn't change too often (especially from an API standpoint) and as @thangngoc89 said, has been stable for a long time.

Also, sorry for the delayed response. I need to figure out my gmail settings to not bury these notifications. 🙄
